// <auto-generated />
namespace Wildlife.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updated_mapdetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updated_mapdetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202103032041049_updated_mapdetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
