// <auto-generated />
namespace Wildlife.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CivicAddress_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CivicAddress_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202102250706476_CivicAddress_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
