// <auto-generated />
namespace Wildlife.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class availability_update1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(availability_update1));
        
        string IMigrationMetadata.Id
        {
            get { return "202103160600030_availability_update1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
